In [22]:
 pip install numpy scikit-learn statsmodels

Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [11]:
import pandas as pd

# Assuming 'BL-Flickr-Images-Book.csv' is your CSV file
df = pd.read_csv('BL-Flickr-Images-Book.csv')
df.head()


Identifier             Edition Statement       Place of Publication  \
0         206                           NaN                     London   
1         216                           NaN  London\t Virtue & Yorston   
2         218                           NaN                     London   
3         472                           NaN                     London   
4         480  A new edition, revised, etc.                     London   

  Date of Publication              Publisher  \
0         1879 [1878]       S. Tinsley & Co.   
1                1868           Virtue & Co.   
2                1869  Bradbury, Evans & Co.   
3                1851          James Darling   
4                1857   Wertheim & Macintosh   

                                               Title     Author  \
0                  Walter Forbes. [A novel.] By A. A      A. A.   
1  All for Greed. [A novel. The dedication signed...  A., A. A.   
2  Love the Avenger. By the author of “All for ...  A., A. A.   
3  Welsh Sketches, chiefly ecclesiastical, to the...  A., E. S.   
4  [The World in which I live, and my place in it...  A., E. S.   

                                   Contributors  Corporate Author  \
0                               FORBES, Walter.               NaN   
1  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN   
2  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN   
3                   Appleyard, Ernest Silvanus.               NaN   
4                           BROOME, John Henry.               NaN   

   Corporate Contributors Former owner  Engraver Issuance type  \
0                     NaN          NaN       NaN   monographic   
1                     NaN          NaN       NaN   monographic   
2                     NaN          NaN       NaN   monographic   
3                     NaN          NaN       NaN   monographic   
4                     NaN          NaN       NaN   monographic   

                                          Flickr URL  \
0  http://www.flickr.com/photos/britishlibrary/ta...   
1  http://www.flickr.com/photos/britishlibrary/ta...   
2  http://www.flickr.com/photos/britishlibrary/ta...   
3  http://www.flickr.com/photos/britishlibrary/ta...   
4  http://www.flickr.com/photos/britishlibrary/ta...   

          Shelfmarks\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  
0  British Library HMNTS 12641.b.30.\t\t\t\t\t\t\...  
1  British Library HMNTS 12626.cc.2.\t\t\t\t\t\t\...  
2  British Library HMNTS 12625.dd.1.\t\t\t\t\t\t\...  
3  British Library HMNTS 10369.bbb.15.\t\t\t\t\t\...  
4  British Library HMNTS 9007.d.28.\t\t\t\t\t\t\t...

In [12]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [24]:
import numpy as np

x = np.array([[5], [15], [25], [35], [45], [55]])
y = np.array([5, 20, 14, 32, 22, 38])


In [15]:
>>> model = LinearRegression()

In [16]:
>>> model.fit(x, y)
LinearRegression()

LinearRegression()

In [17]:
>>> model = LinearRegression().fit(x, y)

In [19]:
>>> r_sq = model.score(x, y)
>>> print(f"coefficient of determination: {r_sq}")


coefficient of determination: 0.715875613747954


In [25]:
 print(f"intercept: {model.intercept_}")

intercept: 5.633333333333329


In [26]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [27]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [28]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [30]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [31]:
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [33]:
 model = LinearRegression().fit(x, y)

In [34]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [35]:
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")

intercept: 5.633333333333329
coefficients: [0.54]


In [36]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [37]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [38]:
x_new = np.arange(10).reshape((-1, 2))
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
x_new = np.array([[10, 20], [30, 40], [50, 60]])
# Reshape x_new to have one feature per row
x_new_reshaped = x_new[:, 0].reshape(-1, 1)

# Or select a single column
x_new_single_column = x_new[:, 0:1]




In [45]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [46]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [47]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [48]:
>>> transformer.fit(x)
PolynomialFeatures(include_bias=False)

PolynomialFeatures(include_bias=False)

In [49]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [52]:
import numpy as np

x_new = np.array([[5., 25.],
                  [15., 225.],
                  [25., 625.],
                  [35., 1225.],
                  [45., 2025.],
                  [55., 3025.]])


In [53]:
>>> model = LinearRegression().fit(x_, y)

In [54]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")


coefficient of determination: 0.8908516262498564
intercept: 21.372321428571425
coefficients: [-1.32357143  0.02839286]


In [55]:
>>> x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [57]:
import numpy as np

x_ = np.array([[1.000e+00, 5.000e+00, 2.500e+01],
               [1.000e+00, 1.500e+01, 2.250e+02],
               [1.000e+00, 2.500e+01, 6.250e+02],
               [1.000e+00, 3.500e+01, 1.225e+03],
               [1.000e+00, 4.500e+01, 2.025e+03],
               [1.000e+00, 5.500e+01, 3.025e+03]])


In [58]:
>>> model = LinearRegression(fit_intercept=False).fit(x_, y)

In [60]:
>>> r_sq = model.score(x_, y)
>>> print(f"coefficient of determination: {r_sq}")

>>> print(f"intercept: {model.intercept_}")
          

>>> print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498565
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [61]:
y_pred = model.predict(x_)
print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [62]:
>>> # Step 1: Import packages and classes
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> from sklearn.preprocessing import PolynomialFeatures

>>> # Step 2a: Provide data
>>> x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]
>>> y = [4, 5, 20, 14, 32, 22, 38, 43]
>>> x, y = np.array(x), np.array(y)

>>> # Step 2b: Transform input data
>>> x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

>>> # Step 3: Create a model and fit it
>>> model = LinearRegression().fit(x_, y)

>>> # Step 4: Get results
>>> r_sq = model.score(x_, y)
>>> intercept, coefficients = model.intercept_, model.coef_

>>> # Step 5: Predict response
>>> y_pred = model.predict(x_)

In [67]:
import numpy as np
import statsmodels.api as sm

In [68]:
>>> x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]
>>> y = [4, 5, 20, 14, 32, 22, 38, 43]
>>> x, y = np.array(x), np.array(y)

In [69]:
x = sm.add_constant(x)

In [70]:
x

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [71]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [72]:
model = sm.OLS(y, x)

In [73]:
results = model.fit()

In [74]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Mon, 04 Mar 2024   Prob (F-statistic):            0.00713
Time:                        14:28:12   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\Users\ishwari\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [76]:
print(f"coefficient of determination: {results.rsquared}")
print(f"adjusted coefficient of determination: {results.rsquared_adj}")
print(f"regression coefficients: {results.params}")


coefficient of determination: 0.8615939258756777
adjusted coefficient of determination: 0.8062314962259488
regression coefficients: [5.52257928 0.44706965 0.25502548]
